
version: '0.0.1'


services:
  app:
    build: .
    restart: on-failure
    ports:
      - 8000:8000
    environment:
      - DATABASE_URL=postgresql+asyncpg://admin:mysecretpassword@db/postgres
    depends_on:
      - db
  db:
    image: postgres:14.4-alpine
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=mysecretpassword
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data:cached